title: Sea Level Rise and At-Risk Areas in Kauai, Hawaii
author: Abigail Brostrom
email: abrostrom@g.ucla.edu
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  This website provides an in-depth look at the at-risk areas on the island of Kauai, Hawaii, for the purpose of real-estate planning.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
